### ISSUE TITLE
Add a link to the documentation of the bunq API?

### ISSUE THREAD

**Issue by eterps** [BeginRescue/bunq#1]
See title, is this documented somewhere? Would make contributions much easier ;-)

**Comment by dunyakirkali** [comment]
I recently contacted support and it appears that they don't currently have a public API 😞

**Comment by eterps** [comment]
They are working on it: https://together.bunq.com/topic/is-there-a-bunq-public-api

**Comment by eterps** [comment]
bunq API is available: https://www.bunq.com/en/news/international-and-api-launch
